

// // Super_Strong_Password
function Super_Strong_Password(){
    let chars = "qwertyuiopasdfghjklzxcvbnm1234567890#$%^&*!{}()@ASDFGHJKLZXCVBNMQWERTYUIOP";
    let password = ""
        for (let i = 0; i <=12; i++) {
            let random = Math.floor((Math.random() * chars.length) + 1);
            password += chars.substring(random,random+1);
        }
        document.getElementById("gen-password-p").value = password
}

function Strong_Password(){
    let chars = "qwertfghjklzxcvbnm1290@ASDFGHJKLZXWERTYUIOP";
    let password = ""
        for (let i = 0; i <=8; i++) {
            let random = Math.floor((Math.random() * chars.length) + 1);
            password += chars.substring(random,random+1);
        }
        document.getElementById("gen-password-p").value = password
}


function Week_Password(){
    let chars = "qwertfghjklzvbnm123ASDFGHJKLZXWERYUIOP";
    let password = ""
        for (let i = 0; i <=5; i++) {
            let random = Math.floor((Math.random() * chars.length) + 1);
            password += chars.substring(random,random+1);
        }
        document.getElementById("gen-password-p").value = password
}

// //  Funny Password 
let funny_btn = document.getElementById("funny_pass")
let funny = ["I Forgot My Password", "password", "KissMyPassword", "Careless User", "IForgot", "NewPassword","ChangeMe",
"NothingAgain",
"SecretUser",
"I Need A Password",
"Password Doctor",
"Right Click",
"Cantre Member",
"Master Password",
"Password Complete",
"This Is Strong",
"Love My Kitten",
"Super Hard Password",
"Very Strong Password",
"Best Password Ever",
"Don't Use My Password",
"Free Wifi",
"Wireless Drop",
"Boring User","mai nhi pataunga","mat pata password",
"Lollipop",
"Sweet Darling",
"SecretCode",
"UnlimitedData",
"Free Hearts",
"DontRushThis",
"DramaQueen",
"PasswordKing",
"Incognito User",
"CameBackSoon",
"TheSunIsOut",
"Glad2BeBalling",
"Sugar Cup",
"LoveYouTooMuch",
"Glad2BeAlive",
"Never Say Never",
"Cotton Candy",
"Silly Bee",
"Honey Bee",
"Sweet Potato",
"Mr. Nice Guy",
"StayWithMe",
"Porcupine",
"BigHeart",
"LoveYouForever",
"CutePasswordUser",
"K-pop SuperFans",
"Fedora D Explorer",
"Just Nuke It",
"Nokia Connecting People",
"Dragon Mother",
"Dont Search For This",
"Cowboy Killer",
"KentuckyFriedChicks",
"LoveMyPopsicles",
"WorksLikeACharm",
"JonSnowWasHere",
"MacLippies",
"HakunaMatata",
"FreezingFriends",
"PlayBoy",
"OreoCookies",
"GuniessRecordHolder",
"ChicagoBullsFan",
"Mustang",
"ShoppingOnEbay",
"Giants",
"Devil Ninja",
"Thunder Bird",
"Harley Davidson",
"Marlboro",
"Diablo007",
"MemorySucks",
"NoMorePassword",
"ColaNotPespi",
"Xerox This",
"Breaking Bad",
"Submitted data",
"Good Passwords Taken",
"Enter New Wifi Name",
"Hotspot Down",
"User Not Secure",
"unique passwords",
"PreciousPassword",
"InternetBadBoy",
"HoustonWeNeedYouHere",
"Force Field",
"HappyBirthdayBaby",
"GoHard Or GoHome",
"LivinDaVidaLoca",
"KaBoom",
"ForTheCulture",
"PasswordChameleon",
"Dancing Baby",
"Space Trooper",
"Mr. Robot",
"DontWorry BeHappy",
"WinterIsHere",
"Taste D Rainbow",
"Big Mac Meal",
"Beam Me Scotty",
"IronMan",
"ChewieGoesHome",
"ThePasswordEffect",
"JustTypeIt",
"HaveANiceTime",
"SorryI'mLate",
"Corvette992",
"Playful Panda",
"Captain America",
"Ferrari Drivers",
"Bond D Ultimate",
"Bad Avenger",
"Nascar",
"Broncos",
"Magnum",
"Jaguar",
"Fragrance",
"Emerald",
"Anaconda",
"Caroline",
"Sultans",
"Nervous",
"Venom",
"Waterway",
"Hero",
"Airplane",
"Ghost",
"Tokyo",
"Santa",
"Winter",
"Chiller",
"Fizzie",
"Gunners",
"Noobs",
"Professionals",
"Warriors",
"Minister",
"Basket",
"Wolverine",
"Leggo",
"Barbie",
"Warcraft",
"Hope",
"Forget",
"Write",
"Wait",
"Save",
"Symbols",
"House",
"PC",
"Phone",
"Group",
"Linksys",
"Tricks",
"Related",
"Three names",
"Wifi aint working",
"Wifi Name Not Found",
"Careless User",
"TriedIt3Times",
"Hahaha",
"KissMyPassword",
"ImTooGood4This",
"I Forgot My Password",
"Hacker Nightmare",
"Call Me Home",
"Error404",
"Invalid Password",
"Wrong Email Entered",
"SomethingNiceForYou",
"UseCarefully",
"TryAgainLater",
"GetYouOwnRouter",
"Where's My Wifi?",
"MoreWifiPlease",
"EnjoyMyDAta",
"YouLikeMyWifi",
"Wifi Password Forgotten",
"Searches Wifi",
"5G Network Here",
"Virus Infected Wifi",
"Guess My Password",
"Try2FigureItOut",
"GoogleItNow",
"Give Me Your Password",
"I Dont Know It Either",
"ideas",
"Password Not Found",
"NobodyHere",
"SuperStrongPassword",
"Let's Be Frank",
"Chilling In Tokyo",
"Coming Back 2 America",
"Say Hello 2 Ma Friends",
"Party All Weekends",
"Kansas Rockstar",
"Elementary Password",
"Found Ma Internet Lover",
"You Stole My Password",
"Password Not Working",
"Hakuna Matata",
"Little Precious Password",
"Baking Soda",
"Amazons Are Online",
"Black And Wifi Wifestores",
"Black And Yellow",
"Wonderful Babies",
"Giants Of Tomorrow",
"East Wood Dragon",
"WildLife Night",
"Disney Monster",
"Silly Sally",
"Devil Loves Gucci",
"KurtCobainLovesMusic",
"NirvanaWasHere",
"EminemAndShady",
"HelterSkelter82",
"Past Ihazwifi Pick",
"Birth Certificate",
"Close Friend",
"Human Mind",
"FreeWifi Wi fi",
"Dog Crap",
"Science fi",
"Hack Nation",
"Bad Computer",
"Hacked Browser",
"StormRider01",
"Server Error",
"DNS Problem",
"CantGiveItToYou",
"Bad Internet Connection",
"ILoveMyWifi",
"Please DontGoWifi",
"CallMeLater",
"ChangeToFactoryReset",
"OverTheMoon",
"ConnecAtNight",
"Unlimited Users Allowed",
"Love Birds Are Here",
"KeepMyPassword",
"DontShareWithAnyone",
"Anonymous User",
"ChangeWifiSettings",
"Joker Face",
"Liquid Metal",
"TigerEyes",
"TheUnforgotten Son",
"Diamonds And Gold",
"WinnerTakesEverything",
"TimeForFinalShowDown",
"BadMusicPlayers",
"The Unforgettable Password",
"SlowRiders",
"Prayer's Secret",
"Lambada",
"Password In Cloud",
"rockstars",
"Beatles",
"DJ Khalid Waz Here",
"Dance Like MJ",
"Hip Pop Rocks",
"Cotton Eye Joe",
"The Temptations Waz Here",
"Galileo Rockstars",
"Walk The Line",
"Aystar D FireStar",
"CardiB Best Fan",
"UnderMyUmbrella",
"BodakYellow",
"ChiliPipers",
"Panda's Password",
"Love My Life",
"Toy Soldiers",
"Hello It's Me",
"Someone Like You",
"Gucci Gang Password",
"Lady In Pink",
"Moon Soon",
"Greatest Dancer Alive",
"Liquid Narc",
"Kiss Of Fire"
]
function Funny_Password(){
    let random =Math.floor((Math.random()*funny.length-1)+1)
    document.getElementById("gen-password-p").value = funny[random]
}

// copy btn
function copyPassword(){
    copyText = document.getElementById("gen-password-p")
    copyText.select()
    document.execCommand("copy")
}










